### ISSUE TITLE
Add dependencies

### ISSUE THREAD

**Issue by Hard-Coder05** [ECellNitrr/ECellApp2021#10]
**Is your feature request related to a problem? Please describe.**
Add required dependencies in the pubspec.yaml file.

**Describe the solution you'd like.**
You can take reference from : https://github.com/ECellNitrr/teesco-app/blob/dev/pubspec.yaml

**Comment by werainkhatri** [comment]
Shouldn't add all the dependency at once. Add them as you go on using them. Add a field in the PR Template where the PR raiser should specify the dependency along with the version that they added, if any.

**Comment by Hard-Coder05** [comment]
> Shouldn't add all the dependency at once. Add them as you go on using them. Add a field in the PR Template where the PR raiser should specify the dependency along with the version that they added, if any.

okay Sir! So I am closing this issue.
