### ISSUE TITLE
Create Constants.dart File

### ISSUE THREAD

**Issue by Hard-Coder05** [ECellNitrr/ECellApp2021#11]
**Is your feature request related to a problem? Please describe.**
Constants.dart file should be located inside the lib folder

**Describe the solution you'd like.**
Reference: https://github.com/ECellNitrr/teesco-app/blob/dev/pubspec.yaml

**Comment by Hard-Coder05** [comment]
Taking up this now.

**Comment by werainkhatri** [comment]
Make a folder "constants" containing basic files like strings.dart, colors.dart, errors.dart for now.

**Comment by Hard-Coder05** [comment]
> Make a folder "constants" containing basic files like strings.dart, colors.dart, errors.dart for now.

okay sir!
