### ISSUE TITLE
Change android package name

### ISSUE THREAD

**Issue by werainkhatri** [ECellNitrr/ECellApp2021#22]
Package name was incorrectly saved to `com.nitrr.ecell.esummit.ecellapp.ecellapp`
Needs to be changed to `com.nitrr.ecell.esummit.ecellapp`

Files to change:
1. build.gradle
2. main/AndroidManifest.xml
3. debug/AndroidManifest.xml
4. profile/AndroidManifest.xml
5. MainActivity.java

Change the location of MainActivity one directory out and delete the last ecellapp directory

**Comment by Hard-Coder05** [comment]
Would like to work on this!

**Comment by werainkhatri** [comment]
> Would like to work on this!

It's ok, I'll do this myself

**Comment by Hard-Coder05** [comment]
> > Would like to work on this!
> 
> It's ok, I'll do this myself

okay sir!!
