### ISSUE TITLE
HomeScreen - Bottom Navigation Bar

### ISSUE THREAD

**Issue by werainkhatri** [ECellNitrr/ECellApp2021#29]
## Description
HomeScreen will consist of bottom navigation bar which will inflate 3 screens,
1. MenuScreen
2. ProfileScreen
3. ContactUsScreen
All the above screens should be `Containers()` for now for now.

## Files
1. screens/home/home.dart
2. screens/home/tabs/<all sub-screens listed above>
3. screens/home/widgets/<all large single widgets>
(If you want to add any other files, lemme know here/slack)

**Comment by Hard-Coder05** [comment]
@werainkhatri I have completed NavBar ! I guess we should move on now, leaving the home screen UI for later. According to me we should complete the cubits as soon as possible for rest other screens till you create one UI screen for reference. What say?

**Comment by werainkhatri** [comment]
I agree. Go on with the cubits.
