### ISSUE TITLE
SignUp Screen -> Cubit

### ISSUE THREAD

**Issue by Hard-Coder05** [ECellNitrr/ECellApp2021#4]
**Is your feature request related to a problem? Please describe.**
Cubit for the SignUp screen.

**Describe the solution you'd like**
1. should have states: initial, loading, success, error, redirect to login (empty function for now).
2. fake api repository.
3. tests.

**Comment by werainkhatri** [comment]
edit the issue description I did for the loginscreen (#3 )

**Comment by Hard-Coder05** [comment]
> edit the issue description I did for the loginscreen (#3 )

@werainkhatri Done!!

**Comment by Hard-Coder05** [comment]
Taking up this issue!

**Comment by werainkhatri** [comment]
Create PRs for issues assigned to you already before assigning new ones.

**Comment by Hard-Coder05** [comment]
> Create PRs for issues assigned to you already before assigning new ones.

done!
