### ISSUE TITLE
ForgetPassword Screen -> Cubit

### ISSUE THREAD

**Issue by Hard-Coder05** [ECellNitrr/ECellApp2021#6]
**Is your feature request related to a problem? Please describe.**
Cubit for the forgetPassword screen.

**Describe the solution you'd like**

1. should have states: initial, loading, success, error.
2. fake api repository.
3. tests.

**Comment by divy-arpit** [comment]
I would like to work on this issue

**Comment by werainkhatri** [comment]
Update on this issue?
