### ISSUE TITLE
Events Screen -> UI and Linking

### ISSUE THREAD

**Issue by Hard-Coder05** [ECellNitrr/ECellApp2021#64]
### Is your feature request related to a problem? Please describe.

Creating the UI of the screen and then linking the completed screen to the correct position in the widget tree of the app.

**Comment by TreavVasu** [comment]
![Screenshot from 2021-02-19 08-05-04](https://user-images.githubusercontent.com/16835617/108449390-6aa1b280-7289-11eb-806c-15588a2a07dd.png)

These APIs don't make sense if you are already sending date and time in Date then why should even give a field time?
@werainkhatri
