### ISSUE TITLE
screen: SplashScreen

### ISSUE THREAD

**Issue by werainkhatri** [ECellNitrr/ECellApp2021#68]
# SplashScreen
### UI:  
animating LoadingWidget (#80) with gradient background ([colors](https://drive.google.com/file/d/1YI45JJuQiF7sZFT_V-Rz66dlPlNPSJv2/view?usp=sharing))
<img src="https://user-images.githubusercontent.com/44755140/107354757-8e7c3000-6af4-11eb-85ef-8c8b10e49cae.png" width="250">

### Logic: 
It should check if the user is logged in (using sharedpreferences) and redirect them to HomeScreen or LoginScreen correspondingly.

**Comment by Hard-Coder05** [comment]
#57 exists for this same issue. Do have a look!

**Comment by Hard-Coder05** [comment]
will make a PR on this today. plz assign me this
