### ISSUE TITLE
SignUp Screen -> API Repository

### ISSUE THREAD

**Issue by Hard-Coder05** [ECellNitrr/ECellApp2021#8]
**Is your feature request related to a problem? Please describe.**
Create API Repository for the SignUp screen.

**Describe the solution you'd like**
1. linking the screen with API calls.

**Comment by Hard-Coder05** [comment]
Taking up this!

**Comment by werainkhatri** [comment]
are the api docs provided by the backend team?

**Comment by Hard-Coder05** [comment]
> are the api docs provided by the backend team?

No sir! not yet. The api docs have not been deployed yet.

**Comment by werainkhatri** [comment]
> Taking up this!

Then how are you taking up this? Wait till the docs are released and then work on it.

**Comment by Hard-Coder05** [comment]
I have recieved the swagger docs! Do assign me this!
