### ISSUE TITLE
Insecure HTTP is not allowed by platform

### ISSUE THREAD

**Issue by TreavVasu** [ECellNitrr/ECellApp2021#84]
### Is your feature request related to a problem? Please describe.

I encountered this problem while testing #56 , The output is attached below.

### Describe the solution you'd like

I would recommend the practice and implementation of steps like the ones mentioned in :

[StackOverflow](https://stackoverflow.com/questions/64197752/bad-state-insecure-http-is-not-allowed-by-platform)

[Medium](https://medium.com/flutter-community/solving-the-new-https-requirements-in-flutter-7abe240fbf23)

### Describe alternatives you've considered

Considering moving on to https can also be an alternative

### Additional context
![Screenshot from 2021-02-10 16-40-02](https://user-images.githubusercontent.com/16835617/107502456-addf8f80-6bbe-11eb-877d-571078d20c99.png)

**Comment by TreavVasu** [comment]
@werainkhatri  Review this issue

**Comment by werainkhatri** [comment]
Is the issue still there after you removed the double forward slashes?

**Comment by TreavVasu** [comment]
Yes it was
