### ISSUE TITLE
Linking Successful Signup and Login Screens

### ISSUE THREAD

**Issue by Hard-Coder05** [ECellNitrr/ECellApp2021#87]
### Describe the bug
After successful Signup user should be taken to Login Screen. But the app shows the screen as shown in the screenshot.

Same happens with the Logi Screen User should be taken to home but the  app shows the screen as shown in the screenshot.
<img width = "250" src="https://user-images.githubusercontent.com/54059881/107542873-a89a3900-6bee-11eb-86d1-dfce50a5dd78.jpg">

**Comment by TreavVasu** [comment]
Add redirect in Listener for the BlocConsumer to redirect to Login

**Comment by Hard-Coder05** [comment]
> Add redirect in Listener for the BlocConsumer to redirect to Login

Yaa working on the same !!

**Comment by TreavVasu** [comment]
> Add redirect in Listener for the BlocConsumer to redirect to Login

Refer to Screen/Login.dart to see the codes to implement it as done with SignUp option in GestureDetector and just implement the same

**Comment by Hard-Coder05** [comment]
@TreavVasu I will link a PR with this issue

**Comment by werainkhatri** [comment]
This is the reason I tell you guys to run the the issue you are taking by me before you start working on it. Linking signup and login is fine, but shared preference checking is to be done in splash screen, and not main.

**Comment by Hard-Coder05** [comment]
> This is the reason I tell you guys to run the the issue you are taking by me before you start working on it. Linking signup and login is fine, but shared preference checking is to be done in splash screen, and not main.

okay sir will keep this in mind next time onwards
